/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package japedidos.pedidos;

/**
 *
 * @author ValentinGomes
 */
public class JFrame_HistoricoPedido extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_HistoricoPedido
     */
    public JFrame_HistoricoPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_incluirPedido = new javax.swing.JPanel();
        jtxtf_valorEntregaHistorico = new javax.swing.JTextField();
        jlbl_horaEntregaHistorico = new javax.swing.JLabel();
        jscp_destinatario = new javax.swing.JScrollPane();
        jtxta_destinatarioHistorico = new javax.swing.JTextArea();
        jtxtf_valorTotalHistorico = new javax.swing.JTextField();
        jtxtf_dataEntregaHistorico = new javax.swing.JTextField();
        jpnl_btn_novo = new javax.swing.JLabel();
        jtxtf_horaEntregaHistorico = new javax.swing.JTextField();
        jcmb_tipoEntregaHistorico = new javax.swing.JComboBox<>();
        jtxtf_nomeClienteHistorico = new javax.swing.JTextField();
        jlbl_valorEntregaHistorico = new javax.swing.JLabel();
        jlbl_bairroHistorico = new javax.swing.JLabel();
        jlbl_ruaHistorico = new javax.swing.JLabel();
        jtxtf_cidadeHistorico = new javax.swing.JTextField();
        jlbl_cidadeHistorico = new javax.swing.JLabel();
        jtxtf_ufHistorico = new javax.swing.JTextField();
        jlbl_tipoEntregaHistorico = new javax.swing.JLabel();
        jtxtf_ruaHistorico = new javax.swing.JTextField();
        jlbl_ufHistorico = new javax.swing.JLabel();
        jtxtf_bairroHistorico = new javax.swing.JTextField();
        jtxtf_descontoHistorico = new javax.swing.JTextField();
        jlbl_descontoHistorico = new javax.swing.JLabel();
        jtxtf_telefoneClienteHistorico = new javax.swing.JTextField();
        jlbl_telefoneClienteHistorico = new javax.swing.JLabel();
        jbtn_criarPedidoHistorico = new javax.swing.JButton();
        jlbl_valorTotalHistorico = new javax.swing.JLabel();
        jlbl_infoAdicionalClienteHistorico = new javax.swing.JLabel();
        jlbl_dataEntregaHistorico = new javax.swing.JLabel();
        jlbl_destinatarioHistorico = new javax.swing.JLabel();
        jlbl_nomeClienteHistorico = new javax.swing.JLabel();
        jtxtf_numeroHistorico = new javax.swing.JTextField();
        jlbl_numeroHistorico = new javax.swing.JLabel();
        jtbl_listaprodutos = new javax.swing.JScrollPane();
        jtbl_lista_produtos = new javax.swing.JTable();
        jpnl_sideMenu = new javax.swing.JPanel();
        jlbl_clientes = new javax.swing.JLabel();
        jlbl_produtos = new javax.swing.JLabel();
        jlbl_pedidos = new javax.swing.JLabel();
        jlbl_relatorios = new javax.swing.JLabel();
        jpnl_img_etiqueta = new javax.swing.JLabel();
        jpnl_background = new javax.swing.JLabel();
        jpnl_background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl_incluirPedido.setOpaque(false);
        jpnl_incluirPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtf_valorEntregaHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_valorEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 120, -1));

        jlbl_horaEntregaHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_horaEntregaHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_horaEntregaHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_horaEntregaHistorico.setText("HORA");
        jpnl_incluirPedido.add(jlbl_horaEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 30));

        jtxta_destinatarioHistorico.setColumns(20);
        jtxta_destinatarioHistorico.setRows(5);
        jscp_destinatario.setViewportView(jtxta_destinatarioHistorico);

        jpnl_incluirPedido.add(jscp_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 260, 60));

        jtxtf_valorTotalHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_valorTotalHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 120, -1));

        jtxtf_dataEntregaHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_dataEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, -1));

        jpnl_btn_novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnl_btn_novoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnl_btn_novoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpnl_btn_novoMouseReleased(evt);
            }
        });
        jpnl_incluirPedido.add(jpnl_btn_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jtxtf_horaEntregaHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_horaEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 90, -1));

        jcmb_tipoEntregaHistorico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Envio", "Retirada no local" }));
        jpnl_incluirPedido.add(jcmb_tipoEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 160, -1));

        jtxtf_nomeClienteHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_nomeClienteHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 300, -1));

        jlbl_valorEntregaHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_valorEntregaHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_valorEntregaHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_valorEntregaHistorico.setText("VALOR DA ENTREGA:");
        jpnl_incluirPedido.add(jlbl_valorEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 190, 30));

        jlbl_bairroHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_bairroHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_bairroHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_bairroHistorico.setText("BAIRRO");
        jpnl_incluirPedido.add(jlbl_bairroHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jlbl_ruaHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_ruaHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_ruaHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_ruaHistorico.setText("RUA");
        jpnl_incluirPedido.add(jlbl_ruaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jtxtf_cidadeHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_cidadeHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 210, -1));

        jlbl_cidadeHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_cidadeHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_cidadeHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cidadeHistorico.setText("CIDADE");
        jpnl_incluirPedido.add(jlbl_cidadeHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jtxtf_ufHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_ufHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 50, -1));

        jlbl_tipoEntregaHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_tipoEntregaHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_tipoEntregaHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_tipoEntregaHistorico.setText("TIPO DA ENTREGA");
        jpnl_incluirPedido.add(jlbl_tipoEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, 30));

        jtxtf_ruaHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_ruaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, -1));

        jlbl_ufHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_ufHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_ufHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_ufHistorico.setText("UF");
        jpnl_incluirPedido.add(jlbl_ufHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        jtxtf_bairroHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_bairroHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 140, -1));

        jtxtf_descontoHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_descontoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 120, -1));

        jlbl_descontoHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_descontoHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_descontoHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_descontoHistorico.setText("DESCONTO APLICADO:");
        jpnl_incluirPedido.add(jlbl_descontoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 200, 30));

        jtxtf_telefoneClienteHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_telefoneClienteHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));

        jlbl_telefoneClienteHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_telefoneClienteHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_telefoneClienteHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_telefoneClienteHistorico.setText("TELEFONE");
        jpnl_incluirPedido.add(jlbl_telefoneClienteHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jbtn_criarPedidoHistorico.setText("Voltar");
        jbtn_criarPedidoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_criarPedidoHistoricoActionPerformed(evt);
            }
        });
        jpnl_incluirPedido.add(jbtn_criarPedidoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 210, -1));

        jlbl_valorTotalHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_valorTotalHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_valorTotalHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_valorTotalHistorico.setText("VALOR TOTAL:");
        jpnl_incluirPedido.add(jlbl_valorTotalHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 130, 30));

        jlbl_infoAdicionalClienteHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/Frame 79 (1).png"))); // NOI18N
        jpnl_incluirPedido.add(jlbl_infoAdicionalClienteHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jlbl_dataEntregaHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_dataEntregaHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_dataEntregaHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_dataEntregaHistorico.setText("DATA");
        jpnl_incluirPedido.add(jlbl_dataEntregaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 30));

        jlbl_destinatarioHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_destinatarioHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_destinatarioHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_destinatarioHistorico.setText("OBSERVAÇÕES");
        jpnl_incluirPedido.add(jlbl_destinatarioHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 160, 30));

        jlbl_nomeClienteHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_nomeClienteHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_nomeClienteHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nomeClienteHistorico.setText("NOME");
        jpnl_incluirPedido.add(jlbl_nomeClienteHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 130, -1));

        jtxtf_numeroHistorico.setForeground(new java.awt.Color(204, 204, 204));
        jpnl_incluirPedido.add(jtxtf_numeroHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 50, -1));

        jlbl_numeroHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_numeroHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_numeroHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_numeroHistorico.setText("Nº");
        jpnl_incluirPedido.add(jlbl_numeroHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jtbl_listaprodutos.setAutoscrolls(true);

        jtbl_lista_produtos.setBackground(new java.awt.Color(153, 204, 255));
        jtbl_lista_produtos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtbl_lista_produtos.setForeground(new java.awt.Color(255, 255, 255));
        jtbl_lista_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Categoria", "Unidade ", "Venda(R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_lista_produtos.setToolTipText("");
        jtbl_lista_produtos.setMinimumSize(new java.awt.Dimension(90, 160));
        jtbl_lista_produtos.setPreferredSize(new java.awt.Dimension(658, 204));
        jtbl_lista_produtos.setShowGrid(false);
        jtbl_lista_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_lista_produtosMouseClicked(evt);
            }
        });
        jtbl_listaprodutos.setViewportView(jtbl_lista_produtos);
        if (jtbl_lista_produtos.getColumnModel().getColumnCount() > 0) {
            jtbl_lista_produtos.getColumnModel().getColumn(0).setPreferredWidth(60);
            jtbl_lista_produtos.getColumnModel().getColumn(1).setPreferredWidth(350);
            jtbl_lista_produtos.getColumnModel().getColumn(4).setPreferredWidth(55);
        }

        jpnl_incluirPedido.add(jtbl_listaprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 730, 190));

        getContentPane().add(jpnl_incluirPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jpnl_sideMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnl_sideMenu.setMaximumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setMinimumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setPreferredSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_clientes.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_clientes.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_clientes.setText("CLIENTES");
        jpnl_sideMenu.add(jlbl_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jlbl_produtos.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_produtos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_produtos.setForeground(new java.awt.Color(204, 204, 204));
        jlbl_produtos.setText("PRODUTOS");
        jlbl_produtos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbl_produtosFocusGained(evt);
            }
        });
        jpnl_sideMenu.add(jlbl_produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jlbl_pedidos.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_pedidos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_pedidos.setText("PEDIDOS");
        jpnl_sideMenu.add(jlbl_pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jlbl_relatorios.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_relatorios.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_relatorios.setText("RELATÓRIOS");
        jpnl_sideMenu.add(jlbl_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jpnl_img_etiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/painel_comandos_esquerda_05x.png"))); // NOI18N
        jpnl_img_etiqueta.setText("jLabel2");
        jpnl_img_etiqueta.setMaximumSize(new java.awt.Dimension(250, 576));
        jpnl_img_etiqueta.setMinimumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.add(jpnl_img_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, -1));

        jpnl_background.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpnl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/background_pedidos.png"))); // NOI18N
        jpnl_background.setToolTipText("");
        jpnl_background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpnl_background.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jpnl_sideMenu.add(jpnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jpnl_sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 576));

        jpnl_background1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpnl_background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/background_pedidos.png"))); // NOI18N
        jpnl_background1.setToolTipText("");
        jpnl_background1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpnl_background1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jpnl_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnl_btn_novoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnl_btn_novoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnl_btn_novoMouseClicked

    private void jpnl_btn_novoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnl_btn_novoMousePressed
        // TODO add your handling code here:
        jpnl_btn_novo.setIcon(new javax.swing.ImageIcon("C:\\SENAI\\TECHNIGHT\\JaPedidos\\JaPedidos\\src\\main\\java\\japedidos\\imagens\\btn_novo_pressionado.png"));
    }//GEN-LAST:event_jpnl_btn_novoMousePressed

    private void jpnl_btn_novoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnl_btn_novoMouseReleased
        // TODO add your handling code here:
        //jpnl_btn_novo.setIcon(new javax.swing.ImageIcon("C:\\JaPedidos\\JaPedidos\\src\\main\\java\\japedidos\\imagens\\btn_novo_padrao.png"));
        jpnl_btn_novo.setIcon(new javax.swing.ImageIcon("C:\\SENAI\\TECHNIGHT\\JaPedidos\\JaPedidos\\src\\main\\java\\japedidos\\imagens\\btn_novo_padrao.png"));
    }//GEN-LAST:event_jpnl_btn_novoMouseReleased

    private void jbtn_criarPedidoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_criarPedidoHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_criarPedidoHistoricoActionPerformed

    private void jlbl_produtosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbl_produtosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbl_produtosFocusGained

    private void jtbl_lista_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_lista_produtosMouseClicked
        // TODO add your handling code here:
        System.out.println( "\n Linha - " + jtbl_lista_produtos.getSelectedRow()+
            "\n Coluna - " + jtbl_lista_produtos.getSelectedColumn()+
            "\n Descricao :  - " + jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(),
                1));

        jtxtf_codigo.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 0));
        jtxtf_descricao.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 1));
        jcmb_categoria.setSelectedItem((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 2));
        jcmb_und.setSelectedItem((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 5));
    }//GEN-LAST:event_jtbl_lista_produtosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_HistoricoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_HistoricoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_HistoricoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_HistoricoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_HistoricoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_criarPedidoHistorico;
    private javax.swing.JComboBox<String> jcmb_tipoEntregaHistorico;
    private javax.swing.JLabel jlbl_bairroHistorico;
    private javax.swing.JLabel jlbl_cidadeHistorico;
    private javax.swing.JLabel jlbl_clientes;
    private javax.swing.JLabel jlbl_dataEntregaHistorico;
    private javax.swing.JLabel jlbl_descontoHistorico;
    private javax.swing.JLabel jlbl_destinatarioHistorico;
    private javax.swing.JLabel jlbl_horaEntregaHistorico;
    private javax.swing.JLabel jlbl_infoAdicionalClienteHistorico;
    private javax.swing.JLabel jlbl_nomeClienteHistorico;
    private javax.swing.JLabel jlbl_numeroHistorico;
    private javax.swing.JLabel jlbl_pedidos;
    private javax.swing.JLabel jlbl_produtos;
    private javax.swing.JLabel jlbl_relatorios;
    private javax.swing.JLabel jlbl_ruaHistorico;
    private javax.swing.JLabel jlbl_telefoneClienteHistorico;
    private javax.swing.JLabel jlbl_tipoEntregaHistorico;
    private javax.swing.JLabel jlbl_ufHistorico;
    private javax.swing.JLabel jlbl_valorEntregaHistorico;
    private javax.swing.JLabel jlbl_valorTotalHistorico;
    private javax.swing.JLabel jpnl_background;
    private javax.swing.JLabel jpnl_background1;
    private javax.swing.JLabel jpnl_btn_novo;
    private javax.swing.JLabel jpnl_img_etiqueta;
    private javax.swing.JPanel jpnl_incluirPedido;
    private javax.swing.JPanel jpnl_sideMenu;
    private javax.swing.JScrollPane jscp_destinatario;
    private javax.swing.JTable jtbl_lista_produtos;
    private javax.swing.JScrollPane jtbl_listaprodutos;
    private javax.swing.JTextArea jtxta_destinatarioHistorico;
    private javax.swing.JTextField jtxtf_bairroHistorico;
    private javax.swing.JTextField jtxtf_cidadeHistorico;
    private javax.swing.JTextField jtxtf_dataEntregaHistorico;
    private javax.swing.JTextField jtxtf_descontoHistorico;
    private javax.swing.JTextField jtxtf_horaEntregaHistorico;
    private javax.swing.JTextField jtxtf_nomeClienteHistorico;
    private javax.swing.JTextField jtxtf_numeroHistorico;
    private javax.swing.JTextField jtxtf_ruaHistorico;
    private javax.swing.JTextField jtxtf_telefoneClienteHistorico;
    private javax.swing.JTextField jtxtf_ufHistorico;
    private javax.swing.JTextField jtxtf_valorEntregaHistorico;
    private javax.swing.JTextField jtxtf_valorTotalHistorico;
    // End of variables declaration//GEN-END:variables
}
