package japedidos.produto;

import japedidos.produto.load_db_2_jtable_jcombbox;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import japedidos.bd.BD;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.text.NumberFormat;
import javax.print.DocFlavor;


public class JFrame_ListaProdutos extends javax.swing.JFrame {
/*
    
    String diretorioBaseImagens = ".\\src\\main\\java\\japedidos\\imagens\\";
    ImageIcon imgBackground_01 = new ImageIcon(diretorioBaseImagens + "\\background_produtos_075x.png");
    */
    
    Color cor_padrao_txt_clientes = new Color(128,128,128);
    Color cor_padrao_txt_produtos = new Color(255,255,255);
    Color cor_padrao_txt_pedidos = new Color(128,128,128);
    Color cor_padrao_txt_relatorios = new Color(128,128,128);
    
    /**
     * Creates new form listaProdutos
     */
    public JFrame_ListaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_sideMenu = new javax.swing.JPanel();
        jtb_linhaBranca = new javax.swing.JToolBar();
        jlbl_clientes = new javax.swing.JLabel();
        jlbl_produtos = new javax.swing.JLabel();
        jlbl_pedidos = new javax.swing.JLabel();
        jlbl_relatorios = new javax.swing.JLabel();
        jpnl_img_etiqueta = new javax.swing.JLabel();
        jpnl_background_01 = new javax.swing.JLabel();
        jpnl_corpo = new javax.swing.JPanel();
        jtb_linhaEncontrar = new javax.swing.JToolBar();
        jlbl_encontrar = new javax.swing.JLabel();
        jtxtf_pesquisa = new javax.swing.JTextField();
        jlbl_descricao = new javax.swing.JLabel();
        ComboBoxTESTE = new javax.swing.JComboBox<>();
        jtxtf_descricao = new javax.swing.JTextField();
        jlbl_categoria = new javax.swing.JLabel();
        jcmb_categoria = new javax.swing.JComboBox<>();
        jlbl_codigo = new javax.swing.JLabel();
        jtxtf_codigo = new javax.swing.JTextField();
        jlbl_unid = new javax.swing.JLabel();
        jcmb_unid = new javax.swing.JComboBox<>();
        jlbl_valor = new javax.swing.JLabel();
        jtxtf_valor = new javax.swing.JTextField();
        jlbl_ativo = new javax.swing.JLabel();
        jchb_ativo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jlbl_btn_novo = new javax.swing.JLabel();
        jlbl_btn_excluir = new javax.swing.JLabel();
        jlbl_btn_salvar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_listaprodutos = new javax.swing.JScrollPane();
        jtbl_lista_produtos = new javax.swing.JTable();
        jpnl_background_02 = new javax.swing.JLabel();
        jtb_linhaBranca1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl_sideMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnl_sideMenu.setMaximumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setMinimumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setPreferredSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtb_linhaBranca.setBackground(new java.awt.Color(255, 255, 255));
        jtb_linhaBranca.setBorder(null);
        jtb_linhaBranca.setForeground(new java.awt.Color(255, 255, 255));
        jtb_linhaBranca.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jtb_linhaBranca.setBorderPainted(false);
        jpnl_sideMenu.add(jtb_linhaBranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 280, 100, 4));

        jlbl_clientes.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_clientes.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_clientes.setForeground(new Color(128,128,128));
        jlbl_clientes.setText("CLIENTES");
        jlbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_clientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbl_clientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbl_clientesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbl_clientesMousePressed(evt);
            }
        });
        jpnl_sideMenu.add(jlbl_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 210, -1, -1));

        jlbl_produtos.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_produtos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_produtos.setForeground(new Color(255,255,255));
        jlbl_produtos.setText("PRODUTOS");
        jlbl_produtos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbl_produtosFocusGained(evt);
            }
        });
        jlbl_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_produtosMouseClicked(evt);
            }
        });
        jpnl_sideMenu.add(jlbl_produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 250, -1, -1));

        jlbl_pedidos.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_pedidos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_pedidos.setForeground(new Color(128,128,128));
        jlbl_pedidos.setText("PEDIDOS");
        jlbl_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_pedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbl_pedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbl_pedidosMouseExited(evt);
            }
        });
        jpnl_sideMenu.add(jlbl_pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 290, -1, -1));

        jlbl_relatorios.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_relatorios.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_relatorios.setForeground(new Color(128,128,128));
        jlbl_relatorios.setText("RELATÓRIOS");
        jlbl_relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_relatoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbl_relatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbl_relatoriosMouseExited(evt);
            }
        });
        jpnl_sideMenu.add(jlbl_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 330, -1, -1));

        jpnl_img_etiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painel_comandos_esquerda_05x.png"))); // NOI18N
        jpnl_img_etiqueta.setMaximumSize(new java.awt.Dimension(250, 576));
        jpnl_img_etiqueta.setMinimumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.add(jpnl_img_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, -1));

        jpnl_background_01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpnl_background_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_produtos_075x.png"))); // NOI18N
        jpnl_background_01.setToolTipText("");
        jpnl_background_01.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpnl_background_01.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jpnl_background_01.setMaximumSize(new java.awt.Dimension(1024, 576));
        jpnl_background_01.setMinimumSize(new java.awt.Dimension(1024, 576));
        jpnl_background_01.setPreferredSize(new java.awt.Dimension(1024, 576));
        jpnl_sideMenu.add(jpnl_background_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jpnl_sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 576));

        jpnl_corpo.setBackground(new java.awt.Color(153, 204, 255));
        jpnl_corpo.setMaximumSize(new java.awt.Dimension(1024, 576));
        jpnl_corpo.setMinimumSize(new java.awt.Dimension(1024, 576));
        jpnl_corpo.setPreferredSize(new java.awt.Dimension(1024, 576));
        jpnl_corpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtb_linhaEncontrar.setBackground(new java.awt.Color(102, 102, 102));
        jtb_linhaEncontrar.setBorder(null);
        jtb_linhaEncontrar.setFloatable(true);
        jtb_linhaEncontrar.setForeground(new java.awt.Color(102, 102, 102));
        jtb_linhaEncontrar.setBorderPainted(false);
        jtb_linhaEncontrar.setEnabled(false);
        jtb_linhaEncontrar.setFocusable(false);
        jtb_linhaEncontrar.setRequestFocusEnabled(false);
        jpnl_corpo.add(jtb_linhaEncontrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 76, 3, 22));

        jlbl_encontrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_encontrar.png"))); // NOI18N
        jlbl_encontrar.setNextFocusableComponent(jtxtf_pesquisa);
        jlbl_encontrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_encontrarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbl_encontrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbl_encontrarMouseReleased(evt);
            }
        });
        jpnl_corpo.add(jlbl_encontrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 76, -1, -1));

        jtxtf_pesquisa.setBackground(new java.awt.Color(204, 204, 204));
        jtxtf_pesquisa.setForeground(new java.awt.Color(102, 102, 102));
        jtxtf_pesquisa.setText("Digite aqui que deseja encontrar e pressione ENTER...");
        jtxtf_pesquisa.setBorder(jtxtf_codigo.getBorder());
        jtxtf_pesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtxtf_pesquisa.setMargin(new java.awt.Insets(2, 54, 2, 6));
        jtxtf_pesquisa.setNextFocusableComponent(jtxtf_codigo);
        jtxtf_pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtf_pesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtf_pesquisaFocusLost(evt);
            }
        });
        jtxtf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_pesquisaActionPerformed(evt);
            }
        });
        jtxtf_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtf_pesquisaKeyTyped(evt);
            }
        });
        jpnl_corpo.add(jtxtf_pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 680, 34));

        jlbl_descricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_descricao.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_descricao.setText("DESCRIÇÃO :");
        jpnl_corpo.add(jlbl_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        ComboBoxTESTE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpnl_corpo.add(ComboBoxTESTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 200, -1));

        jtxtf_descricao.setBackground(new java.awt.Color(204, 204, 204));
        jtxtf_descricao.setForeground(new java.awt.Color(0, 0, 0));
        jtxtf_descricao.setNextFocusableComponent(jcmb_unid);
        jpnl_corpo.add(jtxtf_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 330, 30));

        jlbl_categoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_categoria.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_categoria.setText("CATEGORIA :");
        jpnl_corpo.add(jlbl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        jcmb_categoria.setBackground(new java.awt.Color(102, 102, 102));
        jcmb_categoria.setForeground(new java.awt.Color(204, 204, 204));
        jcmb_categoria.setNextFocusableComponent(jtxtf_valor);
        jcmb_categoria.setPreferredSize(new java.awt.Dimension(400, 22));
        jcmb_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_categoriaActionPerformed(evt);
            }
        });
        jpnl_corpo.add(jcmb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 110, 30));

        jlbl_codigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_codigo.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_codigo.setText("CÓDIGO :");
        jpnl_corpo.add(jlbl_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jtxtf_codigo.setBackground(new java.awt.Color(204, 204, 204));
        jtxtf_codigo.setForeground(new java.awt.Color(0, 0, 0));
        jtxtf_codigo.setNextFocusableComponent(jtxtf_descricao);
        jpnl_corpo.add(jtxtf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 70, 30));

        jlbl_unid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_unid.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_unid.setText("UND :");
        jpnl_corpo.add(jlbl_unid, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 50, -1));

        jcmb_unid.setBackground(new java.awt.Color(102, 102, 102));
        jcmb_unid.setForeground(new java.awt.Color(204, 204, 204));
        jcmb_unid.setBorder(jcmb_categoria.getBorder());
        jcmb_unid.setNextFocusableComponent(jcmb_categoria);
        jcmb_unid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_unidActionPerformed(evt);
            }
        });
        jpnl_corpo.add(jcmb_unid, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 70, 30));

        jlbl_valor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_valor.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_valor.setText("VALOR R$ :");
        jpnl_corpo.add(jlbl_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        jtxtf_valor.setBackground(new java.awt.Color(204, 204, 204));
        jtxtf_valor.setForeground(new java.awt.Color(0, 0, 0));
        jtxtf_valor.setNextFocusableComponent(jlbl_btn_novo);
        jpnl_corpo.add(jtxtf_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 90, 30));

        jlbl_ativo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbl_ativo.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_ativo.setText("ATIVO :");
        jpnl_corpo.add(jlbl_ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 70, -1));
        jpnl_corpo.add(jchb_ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, 30));

        jButton1.setText("TESTE CONSULTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpnl_corpo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        jlbl_btn_novo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_novo_padrao.png"))); // NOI18N
        jlbl_btn_novo.setNextFocusableComponent(jlbl_btn_excluir);
        jlbl_btn_novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_btn_novoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbl_btn_novoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbl_btn_novoMouseReleased(evt);
            }
        });
        jpnl_corpo.add(jlbl_btn_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, -1, -1));

        jlbl_btn_excluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_excluir_padrao.png"))); // NOI18N
        jlbl_btn_excluir.setNextFocusableComponent(jlbl_btn_salvar);
        jlbl_btn_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbl_btn_excluirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbl_btn_excluirMouseReleased(evt);
            }
        });
        jpnl_corpo.add(jlbl_btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, -1, -1));

        jlbl_btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_salvar_padrao.png"))); // NOI18N
        jlbl_btn_salvar.setNextFocusableComponent(jtxtf_pesquisa);
        jlbl_btn_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbl_btn_salvarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbl_btn_salvarMouseReleased(evt);
            }
        });
        jpnl_corpo.add(jlbl_btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, -1, -1));
        jpnl_corpo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jtbl_listaprodutos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jtbl_listaprodutos.setAutoscrolls(true);
        jtbl_listaprodutos.setColumnHeaderView(jtbl_lista_produtos);
        jtbl_listaprodutos.setRowHeaderView(jtbl_lista_produtos);
        jtbl_listaprodutos.setViewportView(jtbl_lista_produtos);

        jtbl_lista_produtos.setBackground(new java.awt.Color(153, 204, 255));
        jtbl_lista_produtos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtbl_lista_produtos.setForeground(new java.awt.Color(255, 255, 255));
        jtbl_lista_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Categoria", "Custo(R$)", "Venda(R$)", "Unidade ", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_lista_produtos.setToolTipText("");
        jtbl_lista_produtos.setMinimumSize(new java.awt.Dimension(90, 160));
        jtbl_lista_produtos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbl_lista_produtos.setShowGrid(false);
        jtbl_lista_produtos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbl_lista_produtosFocusGained(evt);
            }
        });
        jtbl_lista_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_lista_produtosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbl_lista_produtosMousePressed(evt);
            }
        });
        jtbl_listaprodutos.setViewportView(jtbl_lista_produtos);
        if (jtbl_lista_produtos.getColumnModel().getColumnCount() > 0) {
            jtbl_lista_produtos.getColumnModel().getColumn(0).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(0).setPreferredWidth(60);
            jtbl_lista_produtos.getColumnModel().getColumn(1).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(1).setPreferredWidth(352);
            jtbl_lista_produtos.getColumnModel().getColumn(2).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(2).setPreferredWidth(90);
            jtbl_lista_produtos.getColumnModel().getColumn(3).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(3).setPreferredWidth(84);
            jtbl_lista_produtos.getColumnModel().getColumn(4).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(4).setPreferredWidth(84);
            jtbl_lista_produtos.getColumnModel().getColumn(5).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(5).setPreferredWidth(74);
            jtbl_lista_produtos.getColumnModel().getColumn(6).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jpnl_corpo.add(jtbl_listaprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 680, 250));

        jpnl_background_02.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpnl_background_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_produtos_075x.png"))); // NOI18N
        jpnl_background_02.setToolTipText("");
        jpnl_background_02.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpnl_background_02.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jpnl_background_02.setMaximumSize(new java.awt.Dimension(1024, 576));
        jpnl_background_02.setMinimumSize(new java.awt.Dimension(1024, 576));
        jpnl_background_02.setPreferredSize(new java.awt.Dimension(1024, 576));
        jpnl_corpo.add(jpnl_background_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtb_linhaBranca1.setBackground(new java.awt.Color(255, 255, 255));
        jtb_linhaBranca1.setBorder(null);
        jtb_linhaBranca1.setForeground(new java.awt.Color(255, 255, 255));
        jtb_linhaBranca1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jtb_linhaBranca1.setBorderPainted(false);
        jpnl_corpo.add(jtb_linhaBranca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 280, 100, 4));

        getContentPane().add(jpnl_corpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbl_produtosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbl_produtosFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlbl_produtosFocusGained

    private void jlbl_btn_novoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_btn_novoMousePressed
        // TODO add your handling code here:
//        jlbl_btn_novo.setIcon(new javax.swing.ImageIcon(".\\src\\main\\java\\japedidos\\imagens\\btn_novo_pressionado.png")); 
        jlbl_btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_novo_pressionado.png"))); 
        
    }//GEN-LAST:event_jlbl_btn_novoMousePressed

    private void jlbl_btn_novoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_btn_novoMouseClicked
        // TODO add your handling code here:
    

    }//GEN-LAST:event_jlbl_btn_novoMouseClicked

    private void jlbl_btn_novoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_btn_novoMouseReleased
        // TODO add your handling code here:
        jlbl_btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_novo_padrao.png"))); 
    }//GEN-LAST:event_jlbl_btn_novoMouseReleased

    private void jlbl_btn_excluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_btn_excluirMousePressed
        // TODO add your handling code here:
        jlbl_btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_excluir_pressionado.png"))); 
    }//GEN-LAST:event_jlbl_btn_excluirMousePressed

    private void jlbl_btn_excluirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_btn_excluirMouseReleased
        // TODO add your handling code here:
        jlbl_btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_excluir_padrao.png"))); 
    }//GEN-LAST:event_jlbl_btn_excluirMouseReleased

    private void jlbl_btn_salvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_btn_salvarMouseReleased
        // TODO add your handling code here:
        jlbl_btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_salvar_padrao.png"))); 
    }//GEN-LAST:event_jlbl_btn_salvarMouseReleased

    private void jlbl_btn_salvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_btn_salvarMousePressed
        // TODO add your handling code here:
        jlbl_btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_salvar_pressionado.png"))); 
    }//GEN-LAST:event_jlbl_btn_salvarMousePressed

    private void jlbl_clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_clientesMouseEntered
        // TODO add your handling code here:
        jlbl_clientes.setForeground(new Color(187,187,187));
        
    }//GEN-LAST:event_jlbl_clientesMouseEntered

    private void jlbl_clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_clientesMouseExited
        // TODO add your handling code here:
        jlbl_clientes.setForeground(new Color(128,128,128));
    }//GEN-LAST:event_jlbl_clientesMouseExited

    private void jlbl_pedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_pedidosMouseExited
        // TODO add your handling code here:
        if (jlbl_pedidos.getForeground().equals(new Color(255, 255, 255)) ){
             jlbl_pedidos.setForeground(new Color(128,128,128));
         }
    }//GEN-LAST:event_jlbl_pedidosMouseExited

    private void jlbl_pedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_pedidosMouseEntered
        // TODO add your handling code here:
        jlbl_pedidos.setForeground(new Color(187,187,187));
    }//GEN-LAST:event_jlbl_pedidosMouseEntered

    private void jlbl_relatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_relatoriosMouseEntered
        // TODO add your handling code here:
        jlbl_relatorios.setForeground(new Color(187,187,187));
    }//GEN-LAST:event_jlbl_relatoriosMouseEntered

    private void jlbl_relatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_relatoriosMouseExited
        // TODO add your handling code here:
        //jlbl_relatorios.setForeground(new Color(128,128,128));
        if (cor_padrao_txt_relatorios!= new Color(255,255,255)){
            jlbl_relatorios.setForeground(new Color(128,128,128));
        } else {
        }
    }//GEN-LAST:event_jlbl_relatoriosMouseExited

    private void jlbl_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_clientesMousePressed
        // TODO add your handling code here:
        //jtb_linhaBranca.locate(46, 240);
    }//GEN-LAST:event_jlbl_clientesMousePressed

    private void jlbl_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_clientesMouseClicked
        // TODO add your handling code here:
        cor_padrao_txt_clientes = new Color(255,255,255);
        jlbl_clientes.setForeground(cor_padrao_txt_clientes);
        
        cor_padrao_txt_produtos = new Color(128,128,128);
        cor_padrao_txt_pedidos = new Color(128,128,128);
        cor_padrao_txt_relatorios = new Color(128,128,128);

        
        
        
//        jtb_linhaBranca.setSize(jlbl_clientes.getWidth(), 4 );
//        jlbl_clientes.setForeground(new Color(255,255,255));
        
        jlbl_pedidos.setForeground(new Color(128,128,128));
        jlbl_produtos.setForeground(new Color(128,128,128));
        jlbl_relatorios.setForeground(new Color(128,128,128));
        
    }//GEN-LAST:event_jlbl_clientesMouseClicked

    private void jlbl_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_produtosMouseClicked
        // TODO add your handling code here:
        jtb_linhaBranca.setLocation(46, 250+30);
        jtb_linhaBranca.setSize(jlbl_produtos.getWidth(), 4 );
        jlbl_produtos.setForeground(new Color(255,255,255));

    }//GEN-LAST:event_jlbl_produtosMouseClicked

    private void jlbl_pedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_pedidosMouseClicked
        // TODO add your handling code here:
        jtb_linhaBranca.setLocation(46, 290+30);
        jtb_linhaBranca.setSize(jlbl_pedidos.getWidth(), 4 );
        jlbl_pedidos.setForeground(new Color(255,255,255));
        
    }//GEN-LAST:event_jlbl_pedidosMouseClicked

    private void jlbl_relatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_relatoriosMouseClicked
        // TODO add your handling code here:
        jtb_linhaBranca.setLocation(46, 330+30);
        jtb_linhaBranca.setSize(jlbl_relatorios.getWidth(), 4 );
        jlbl_relatorios.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jlbl_relatoriosMouseClicked

    private void jtbl_lista_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_lista_produtosMouseClicked
        // TODO add your handling code here:
        if (jtbl_lista_produtos.getRowCount()>=1){
            
            NumberFormat formatter = NumberFormat.getCurrencyInstance();
            NumberFormat decimal = new DecimalFormat("#,##0.00"); 
/*
            System.out.println( "\n Linha - " + jtbl_lista_produtos.getSelectedRow()+
                                "\n Coluna - " + jtbl_lista_produtos.getSelectedColumn()+
                                "\n Descricao :  - " + jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 
                                                    1));
            */
            jtxtf_codigo.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 0));
            jtxtf_descricao.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 1));
            jcmb_categoria.setSelectedItem((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 2));
            jcmb_unid.setSelectedItem((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 5));
            jtxtf_valor.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 4));  //quase ok
            
            ComboBoxTESTE.setSelectedItem((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 2));
        };
    }//GEN-LAST:event_jtbl_lista_produtosMouseClicked

    private void jtxtf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_pesquisaActionPerformed
        // TODO add your handling code here:
//          String sql_lista_produtos_view = "select * from produto group by nome having nome LIKE '%PIZZA%'";
          //String encontrar = jtxtf_pesquisa.getText();
          String sql_lista_produtos_view = "select * from listaTodosProdutos group by nome having nome LIKE ";
          

        Connection conexao = null;
        PreparedStatement statement = null;
        String url = "jdbc:mysql://localhost:3306/titanw25_japedidos_hml";
        String usuario = "root";
        String senha = "";
/*
        String url = "jdbc:mysql://162.241.203.86:3306/titanw25_japedidos_hml";
        String usuario = "titanw25_japedidos_hml";
        String senha = "seNai@2024proj";
        */
        try
        {
            String encontrar = jtxtf_pesquisa.getText();
            
            sql_lista_produtos_view = sql_lista_produtos_view + "'%" +
                                                                encontrar + "%'" + " or categoria LIKE " +
                                                                "'%" + encontrar + "%'" + " ORDER BY nome ASC";

            conexao = DriverManager.getConnection(url, usuario, senha);
            statement = conexao.prepareStatement(sql_lista_produtos_view);
/*
            String encontrar = jtxtf_pesquisa.getText();
            System.out.println("Texto = " + encontrar);
            statement.setString(1, encontrar);
*/
                    
            statement.execute();
            ResultSet resultado = statement.executeQuery(sql_lista_produtos_view);

            DefaultTableModel model =(DefaultTableModel) jtbl_lista_produtos.getModel();
            model.setNumRows(0);
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();



            while(resultado.next())
            {
                model.addRow(new Object[] 
                { 
                   //retorna os dados da tabela do BD, cada campo e um coluna.
                   resultado.getString("id"),
                   resultado.getString("nome"),
                   resultado.getString("categoria"),
//                   resultado.getDouble("preco_custo"),
                   resultado.getBigDecimal("preco_custo"),
                   resultado.getDouble("preco_venda"),
                   resultado.getString("unidade"),
                   resultado.getBoolean("estado")
                }); 
           } 
            statement.close();
            statement.close();
        }
          catch (SQLException ex)
          {
             System.out.println("o erro foi " +ex);
            }        
    }//GEN-LAST:event_jtxtf_pesquisaActionPerformed

    private void jtxtf_pesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtf_pesquisaFocusGained
        // TODO add your handling code here:
        jtxtf_pesquisa.setText("");
    }//GEN-LAST:event_jtxtf_pesquisaFocusGained

    private void jtxtf_pesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtf_pesquisaFocusLost
        // TODO add your handling code here:
        jtxtf_pesquisa.setText("Digite aqui que deseja encontrar e pressione ENTER...");
    }//GEN-LAST:event_jtxtf_pesquisaFocusLost

    private void jlbl_encontrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_encontrarMousePressed
        // TODO add your handling code here:
        jlbl_encontrar.setIcon(new javax.swing.ImageIcon(".\\src\\main\\java\\japedidos\\imagens\\icon_encontrar_pressionado.png")); 
    }//GEN-LAST:event_jlbl_encontrarMousePressed

    private void jlbl_encontrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_encontrarMouseReleased
        // TODO add your handling code here:
        jlbl_encontrar.setIcon(new javax.swing.ImageIcon(".\\src\\main\\java\\japedidos\\imagens\\icon_encontrar_padrao.png")); 
    }//GEN-LAST:event_jlbl_encontrarMouseReleased

    private void jlbl_encontrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_encontrarMouseClicked
        String encontrar = jtxtf_pesquisa.getText();
        String sql_lista_produtos_view = "";

        encontrar = "'%" + encontrar + "%'";
        if (jtxtf_pesquisa.getText().equals("")|jtxtf_pesquisa.getText().equals("Digite aqui que deseja encontrar...")){
            sql_lista_produtos_view = "select * from listaTodosProdutos group by nome ";
        } else {
            sql_lista_produtos_view = "select * from listaTodosProdutos group by nome having nome LIKE " + encontrar;
        }
               

        Connection conexao = null;
        PreparedStatement statement = null;

        String url = "jdbc:mysql://localhost:3306/titanw25_japedidos_hml";
        String usuario = "root";
        String senha = "";
/*
        String url = "jdbc:mysql://162.241.203.86:3306/titanw25_japedidos_hml";
        String usuario = "titanw25_japedidos_hml";
        String senha = "seNai@2024proj";
        */
        try
        {
            conexao = DriverManager.getConnection(url, usuario, senha);
            statement = conexao.prepareStatement(sql_lista_produtos_view);

            statement.execute();
            ResultSet resultado = statement.executeQuery(sql_lista_produtos_view);

            DefaultTableModel model =(DefaultTableModel) jtbl_lista_produtos.getModel();
            model.setRowCount(0);
            model.setNumRows(0);

            while(resultado.next())
            {
                model.addRow(new Object[] 
                { 
                   //retorna os dados da tabela do BD, cada campo e um coluna.
                   resultado.getString("id"),
                   resultado.getString("nome"),
                   resultado.getString("categoria"),
                   resultado.getDouble("preco_custo"),
                   resultado.getDouble("preco_venda"),
                   resultado.getString("unidade"),
                   resultado.getBoolean("estado")
                }); 
           } 
            statement.close();
        }
          catch (SQLException ex)
          {
             System.out.println("o erro foi " +ex);
            }
        
    }//GEN-LAST:event_jlbl_encontrarMouseClicked

    private void jtxtf_pesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtf_pesquisaKeyTyped
/*
NumberFormat formatter = NumberFormat.getCurrencyInstance();
        
        if ( (jtxtf_pesquisa.getText().length()>=2) & (!jtxtf_pesquisa.getText().equals("Digite aqui que deseja encontrar...")) ){
        String encontrar = jtxtf_pesquisa.getText();
        String sql_lista_produtos_view = "";
        
        encontrar = "'%" + encontrar + "%'";
        sql_lista_produtos_view = "select * from listaTodosProdutos group by nome having nome LIKE " + encontrar;
                      

        Connection conexao = null;
        PreparedStatement statement = null;

//        String url = "jdbc:mysql://localhost:3306/titanw25_japedidos_hml";
//        String usuario = "root";
//        String senha = "";

        String url = "jdbc:mysql://162.241.203.86:3306/titanw25_japedidos_hml";
        String usuario = "titanw25_japedidos_hml";
        String senha = "seNai@2024proj";
  
        try
        {
            conexao = DriverManager.getConnection(url, usuario, senha);
            statement = conexao.prepareStatement(sql_lista_produtos_view);

            statement.execute();
            ResultSet resultado = statement.executeQuery(sql_lista_produtos_view);
            

//            String encontrar = jtxtf_pesquisa.getText();
//          System.out.println("Texto = " + encontrar);
//          statement.setString(1, encontrar);
//

            DefaultTableModel model =(DefaultTableModel) jtbl_lista_produtos.getModel();
            model.setRowCount(0);
            model.setNumRows(0);

            while(resultado.next())
            {
                model.addRow(new Object[] 
                { 
                   //retorna os dados da tabela do BD, cada campo e um coluna.
                   resultado.getString("id"),
                   resultado.getString("nome"),
                   resultado.getString("categoria"),
                   resultado.getDouble("preco_custo"),
                   resultado.getDouble("preco_venda"),
                   resultado.getString("unidade"),
                   resultado.getBoolean("estado")
                }); 
           } 
            statement.close();
        }
          catch (SQLException ex)
          {
             System.out.println("o erro foi : " +ex);
            }
        
            
        }
*/      
    }//GEN-LAST:event_jtxtf_pesquisaKeyTyped

    private void jcmb_unidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_unidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_unidActionPerformed

    private void jcmb_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_categoriaActionPerformed
        // TODO add your handling code here:
        // Codigo executado todas as vezes que um evento é chamado para este componente.
/*        
                System.out.println(  "\n Contagem - " + jcmb_categoria.getItemCount()+
                                                "\n getActionListeners - " + jcmb_categoria.getActionListeners()+
                                                "\n getSelectedIndex - " + jcmb_categoria.getSelectedIndex()+
                                                "\n getSelectedItem - " + jcmb_categoria.getSelectedItem()
                                                );
*/
    }//GEN-LAST:event_jcmb_categoriaActionPerformed

    private void jtbl_lista_produtosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_lista_produtosMousePressed
        if (jtbl_lista_produtos.getRowCount()>=1){
            
            NumberFormat formatter = NumberFormat.getCurrencyInstance();
            NumberFormat decimal = new DecimalFormat("#,##0.00"); 
/*
            System.out.println( "\n Linha - " + jtbl_lista_produtos.getSelectedRow()+
                                "\n Coluna - " + jtbl_lista_produtos.getSelectedColumn()+
                                "\n Descricao :  - " + jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 
                                                    1));
            */
            jtxtf_codigo.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 0));
            jtxtf_descricao.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 1));
            jcmb_categoria.setSelectedItem((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 2));
            jcmb_unid.setSelectedItem((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 5));
            jtxtf_valor.setText((String) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 4));  //quase ok
            jchb_ativo.setSelected(Boolean.parseBoolean( jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 6)));
            //ComboBoxTESTE.setSelectedItem((boolean) jtbl_lista_produtos.getValueAt(jtbl_lista_produtos.getSelectedRow(), 2));
        };
   
    }//GEN-LAST:event_jtbl_lista_produtosMousePressed

    private void jtbl_lista_produtosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbl_lista_produtosFocusGained
    }//GEN-LAST:event_jtbl_lista_produtosFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NumberFormat decimal = new DecimalFormat("#,##0.00");
        Connection banco = null;
//        PreparedStatement stm_lista_produtos_view = null;
        
        HashMap<Integer, String[]> categoriaMap = new HashMap<>();
        HashMap<Integer, String[]> unidadeMap = new HashMap<>();
        //
        String url = "jdbc:mysql://localhost:3306/titanw25_japedidos_hml";
        String usuario = "root";
        String senha = "";
        //        String url = "jdbc:mysql://162.241.203.86:3306/titanw25_japedidos_hml";
        //       String usuario = "titanw25_japedidos_hml";
        //      String senha = "seNai@2024proj";
        try (Connection conn = DriverManager.getConnection(url, usuario, senha)) {
            String sqlQuery = "SELECT id, nome, descricao FROM categoria ORDER BY nome ASC"; // Exemplo de consulta

            load_db_2_jtable_jcombbox.loadComboBox(ComboBoxTESTE, conn, sqlQuery);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        try
        {
            banco = DriverManager.getConnection(url, usuario, senha);
            String sql_lista_produtos_view = "SELECT * FROM listaTodosProdutos ORDER BY nome ASC";
            String sql_categoria = "SELECT id, nome, descricao FROM categoria ORDER BY nome ASC";
            String sql_unidade = "SELECT id, abreviacao FROM unidade ORDER BY abreviacao ASC";
            
            PreparedStatement stm_lista_produtos_view = banco.prepareStatement(sql_lista_produtos_view);
            PreparedStatement stm_categoria = banco.prepareStatement(sql_categoria);            
            PreparedStatement stm_unidade = banco.prepareStatement(sql_unidade);
            
//            stm_lista_produtos_view.execute(); // cria o vetor
            ResultSet resultado_lista_produtos_view = stm_lista_produtos_view.executeQuery(sql_lista_produtos_view);
            ResultSet resultado_categoria = stm_categoria.executeQuery();
            ResultSet resultado_unidade = stm_unidade.executeQuery();

//          Define modelo de tabela a partir da  que ja existe neste frame
            DefaultTableModel model =(DefaultTableModel) jtbl_lista_produtos.getModel();
//          Zera a lista caso ja exista algum dado anterior
            model.setRowCount(0);
            while(resultado_lista_produtos_view.next())
            {
                model.addRow(new Object[]
                    {
                        //  Retorna os dados da tabela do lista_produtos_view, cada campo e um coluna.
                        resultado_lista_produtos_view.getString("id"),
                        resultado_lista_produtos_view.getString("nome"),
                        resultado_lista_produtos_view.getString("categoria"),
                        decimal.format(resultado_lista_produtos_view.getDouble("preco_custo")),
                        decimal.format(resultado_lista_produtos_view.getDouble("preco_venda")),
                        resultado_lista_produtos_view.getString("unidade"),
                        resultado_lista_produtos_view.getBoolean("estado")
                    });
                }
            while (resultado_categoria.next()) {
                int index = resultado_categoria.getInt("id");  // Obtém o índice
                String nomeCategoria = resultado_categoria.getString("nome");  // Obtém o nome
//                  String nomeDescricao = resultado.getString("descricao");  // Obtém o descricao
//                  categoriaMap.put(index, nomeCategoria);
//                  categoriaMap.put(index, new String[]{nomeCategoria, nomeDescricao});
                categoriaMap.put(index, new String[]{nomeCategoria});
//                  Adiciona o nome ao JComboBox
                jcmb_categoria.addItem(nomeCategoria);
            }
            while (resultado_unidade.next()) {
                int index = resultado_unidade.getInt("id");  // Obtém o índice
                String nomeUnidade = resultado_unidade.getString("abreviacao");  // Obtém o nome
                unidadeMap.put(index, new String[]{nomeUnidade});
                jcmb_unid.addItem(nomeUnidade);
            }
            
            stm_unidade.close();
            stm_categoria.close();
            stm_lista_produtos_view.close();
            }
            catch (SQLException ex)
            {
                System.out.println("O erro foi  X:  " +ex);
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        Path currentRelativePath = Paths.get("");
        String caminhoImagens = currentRelativePath.toAbsolutePath().toString();
        caminhoImagens = Paths.get(".").toAbsolutePath().normalize().toString();
        System.out.print("O diretorio atual : " + caminhoImagens + "\n");
        
                
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_ListaProdutos().setVisible(true);
                    Color cor_padrao_txt_clientes = new Color(128,128,128);
                    Color cor_padrao_txt_produtos = new Color(255,255,255);
                    Color cor_padrao_txt_pedidos = new Color(128,128,128);
                    Color cor_padrao_txt_relatorios = new Color(128,128,128);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTESTE;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jchb_ativo;
    private javax.swing.JComboBox<String> jcmb_categoria;
    private javax.swing.JComboBox<String> jcmb_unid;
    private javax.swing.JLabel jlbl_ativo;
    private javax.swing.JLabel jlbl_btn_excluir;
    private javax.swing.JLabel jlbl_btn_novo;
    private javax.swing.JLabel jlbl_btn_salvar;
    private javax.swing.JLabel jlbl_categoria;
    private javax.swing.JLabel jlbl_clientes;
    private javax.swing.JLabel jlbl_codigo;
    private javax.swing.JLabel jlbl_descricao;
    private javax.swing.JLabel jlbl_encontrar;
    private javax.swing.JLabel jlbl_pedidos;
    private javax.swing.JLabel jlbl_produtos;
    private javax.swing.JLabel jlbl_relatorios;
    private javax.swing.JLabel jlbl_unid;
    private javax.swing.JLabel jlbl_valor;
    private javax.swing.JLabel jpnl_background_01;
    private javax.swing.JLabel jpnl_background_02;
    private javax.swing.JPanel jpnl_corpo;
    private javax.swing.JLabel jpnl_img_etiqueta;
    private javax.swing.JPanel jpnl_sideMenu;
    private javax.swing.JToolBar jtb_linhaBranca;
    private javax.swing.JToolBar jtb_linhaBranca1;
    private javax.swing.JToolBar jtb_linhaEncontrar;
    private javax.swing.JTable jtbl_lista_produtos;
    private javax.swing.JScrollPane jtbl_listaprodutos;
    private javax.swing.JTextField jtxtf_codigo;
    private javax.swing.JTextField jtxtf_descricao;
    private javax.swing.JTextField jtxtf_pesquisa;
    private javax.swing.JTextField jtxtf_valor;
    // End of variables declaration//GEN-END:variables

}
