/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package japedidos.produto;

import japedidos.bd.BD;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.JTable;
import javax.swing.JOptionPane;
/**
 *
 * @author thiago
 */
public class JFrame_Categoria extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Categoria
     */
    public JFrame_Categoria() {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        jtbl_categoria.getModel().fillRows(BD.Categoria.selectAll());
        
        JTable table = jtbl_categoria.getJTable();
        table.getSelectionModel().addListSelectionListener((e) -> {
            int selRow = table.getSelectedRow();
            if (selRow != -1) {
                Categoria categoriaSelecionada = jtbl_categoria.getModel().getRow(selRow);
                this.setFieldsInfo(categoriaSelecionada);
            }
        });
    }
    
    private void clearFieldsInfo() {
        jtxtf_id.setText(null);
        jtxtf_nome.setText(null);
        jtxtf_descricao.setText(null);
    }
    
    private void setFieldsInfo(Categoria categoria) {
        if (categoria == null) {
            throw new NullPointerException();
        }
        
        jtxtf_id.setText(String.valueOf(categoria.getId()));
        jtxtf_nome.setText(categoria.getNome());
        jtxtf_descricao.setText(categoria.getDescricao());
    }
    
    private Categoria getFieldsInfo() {
        String nome = jtxtf_nome.getText().trim();
        String descricao = jtxtf_descricao.getText().trim();
        
        if (nome.isEmpty()) {
            return null;
        }
        
        Categoria categoria;
        try {
            int id = Integer.parseInt(jtxtf_id.getText().trim()); // Throw se id for vazio ou não-inteiro
            categoria = new Categoria(id, nome, descricao);
        } catch (NumberFormatException e) {
            categoria = new Categoria(nome, descricao);
        }
        return categoria;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtbl_categoria = new japedidos.produto.JTable_Categoria();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtf_nome = new javax.swing.JTextField();
        jtxtf_id = new javax.swing.JTextField();
        jtxtf_descricao = new javax.swing.JTextField();
        jbtn_inserir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtn_limparSelecao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categoria");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jtbl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 180));

        jLabel1.setText("Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel3.setText("Descrição");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));
        jPanel1.add(jtxtf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 200, -1));
        jPanel1.add(jtxtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, -1));
        jPanel1.add(jtxtf_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 140, -1));

        jbtn_inserir.setText("Inserir");
        jbtn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_inserirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 520, 10));

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 110, -1));

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 120, -1));

        jbtn_limparSelecao.setText("Limpar seleção");
        jbtn_limparSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limparSelecaoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_limparSelecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 180, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_inserirActionPerformed
        
        Categoria newCategoria = this.getFieldsInfo();
        if (BD.Categoria.insert(newCategoria) > 0) {
            jtbl_categoria.refresh();
            this.clearFieldsInfo();
        }
    }//GEN-LAST:event_jbtn_inserirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(BD.Categoria.update(this.getFieldsInfo()) == 0) {
            JOptionPane.showMessageDialog(null, "O item especificado não foi encontrado.");
            this.clearFieldsInfo();
        } else {
            jtbl_categoria.refresh();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (BD.Categoria.delete(this.getFieldsInfo()) == 0) {
            JOptionPane.showMessageDialog(null, "Não é possível excluir o item novamente.");
        } else {
            jtbl_categoria.refresh();
        }
        
        this.clearFieldsInfo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtn_limparSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limparSelecaoActionPerformed
        clearFieldsInfo();
        jtbl_categoria.getJTable().getSelectionModel().clearSelection();
    }//GEN-LAST:event_jbtn_limparSelecaoActionPerformed

    public int getSelectedRow() {
        return jtbl_categoria.getJTable().getSelectedRow();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Categoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtn_inserir;
    private javax.swing.JButton jbtn_limparSelecao;
    private japedidos.produto.JTable_Categoria jtbl_categoria;
    private javax.swing.JTextField jtxtf_descricao;
    private javax.swing.JTextField jtxtf_id;
    private javax.swing.JTextField jtxtf_nome;
    // End of variables declaration//GEN-END:variables
}
