package japedidos.produto;

import java.awt.Color;

public class listaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form listaProdutos
     */
    public listaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpnl_sideMenu = new javax.swing.JPanel();
        jlbl_clientes = new javax.swing.JLabel();
        jlbl_produtos = new javax.swing.JLabel();
        jlbl_pedidos = new javax.swing.JLabel();
        jlbl_relatorios = new javax.swing.JLabel();
        jpnl_img_etiqueta = new javax.swing.JLabel();
        jpnl_background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_lista_produtos = new javax.swing.JTable();
        jpnl_btn_excluir = new javax.swing.JLabel();
        jpnl_btn_salvar = new javax.swing.JLabel();
        jpnl_btn_novo = new javax.swing.JLabel();
        jpnl_background1 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/background_produtos_075x.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(1024, 576));
        jLabel3.setMinimumSize(new java.awt.Dimension(1024, 576));
        jLabel3.setPreferredSize(new java.awt.Dimension(1024, 576));
        jLabel3.getAccessibleContext().setAccessibleParent(jpnl_img_etiqueta);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1024, 576));
        setSize(new java.awt.Dimension(1024, 576));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl_sideMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnl_sideMenu.setMaximumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setMinimumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setPreferredSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_clientes.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_clientes.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_clientes.setText("CLIENTES");
        jpnl_sideMenu.add(jlbl_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jlbl_produtos.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_produtos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_produtos.setForeground(new java.awt.Color(204, 204, 204));
        jlbl_produtos.setText("PRODUTOS");
        jlbl_produtos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbl_produtosFocusGained(evt);
            }
        });
        jpnl_sideMenu.add(jlbl_produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jlbl_pedidos.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_pedidos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_pedidos.setText("PEDIDOS");
        jpnl_sideMenu.add(jlbl_pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jlbl_relatorios.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_relatorios.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jlbl_relatorios.setText("RELATÓRIOS");
        jpnl_sideMenu.add(jlbl_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jpnl_img_etiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/painel_comandos_esquerda_05x.png"))); // NOI18N
        jpnl_img_etiqueta.setText("jLabel2");
        jpnl_img_etiqueta.setMaximumSize(new java.awt.Dimension(250, 576));
        jpnl_img_etiqueta.setMinimumSize(new java.awt.Dimension(250, 576));
        jpnl_sideMenu.add(jpnl_img_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, -1));

        jpnl_background.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpnl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/background_produtos_075x.png"))); // NOI18N
        jpnl_background.setToolTipText("");
        jpnl_background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpnl_background.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jpnl_sideMenu.add(jpnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jpnl_sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 576));

        jtbl_lista_produtos.setBackground(new java.awt.Color(153, 204, 255));
        jtbl_lista_produtos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtbl_lista_produtos.setForeground(new java.awt.Color(255, 255, 255));
        jtbl_lista_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "BOLINHA DE QUEIJO", "ALIMENTO",  new Double(0.75), "UND",  new Boolean(true)},
                { new Integer(2), "COXINHA DE FRANGO", "ALIMENTO",  new Double(0.75), "UND",  new Boolean(true)},
                { new Integer(3), "KIBE DE CARNE", "ALIMENTO",  new Double(0.65), "UND",  new Boolean(true)},
                { new Integer(4), "RISSOLE DE PIZZA", "ALIMENTO",  new Double(0.65), "UND",  new Boolean(true)},
                { new Integer(5), "RISSOLE DE CAMARÃO", "ALIMENTO",  new Double(0.75), "UND",  new Boolean(true)},
                { new Integer(6), "MINI CHURROS", "ALIMENTO",  new Double(0.55), "UND",  new Boolean(true)},
                { new Integer(7), "ENROLADO DE SALSICHA ", "ALIMENTO",  new Double(0.55), "UND",  new Boolean(true)}
            },
            new String [] {
                "Codigo", "Descrição", "Categoria", "Valor(R$)", "Unidade ", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbl_lista_produtos.setMinimumSize(new java.awt.Dimension(90, 160));
        jtbl_lista_produtos.setPreferredSize(new java.awt.Dimension(655, 204));
        jScrollPane1.setViewportView(jtbl_lista_produtos);
        if (jtbl_lista_produtos.getColumnModel().getColumnCount() > 0) {
            jtbl_lista_produtos.getColumnModel().getColumn(0).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(0).setPreferredWidth(60);
            jtbl_lista_produtos.getColumnModel().getColumn(1).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(1).setPreferredWidth(350);
            jtbl_lista_produtos.getColumnModel().getColumn(2).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(2).setPreferredWidth(90);
            jtbl_lista_produtos.getColumnModel().getColumn(3).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(3).setPreferredWidth(60);
            jtbl_lista_produtos.getColumnModel().getColumn(4).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(4).setPreferredWidth(55);
            jtbl_lista_produtos.getColumnModel().getColumn(5).setResizable(false);
            jtbl_lista_produtos.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 262, 664, 170));

        jpnl_btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/btn_excluir_padrao.png"))); // NOI18N
        jPanel1.add(jpnl_btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        jpnl_btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/btn_salvar_padrao.png"))); // NOI18N
        jPanel1.add(jpnl_btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, -1, -1));

        jpnl_btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/btn_novo_padrao.png"))); // NOI18N
        jPanel1.add(jpnl_btn_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        jpnl_background1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpnl_background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japedidos/imagens/background_produtos_075x.png"))); // NOI18N
        jpnl_background1.setToolTipText("");
        jpnl_background1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpnl_background1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jpnl_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbl_produtosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbl_produtosFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlbl_produtosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbl_clientes;
    private javax.swing.JLabel jlbl_pedidos;
    private javax.swing.JLabel jlbl_produtos;
    private javax.swing.JLabel jlbl_relatorios;
    private javax.swing.JLabel jpnl_background;
    private javax.swing.JLabel jpnl_background1;
    private javax.swing.JLabel jpnl_btn_excluir;
    private javax.swing.JLabel jpnl_btn_novo;
    private javax.swing.JLabel jpnl_btn_salvar;
    private javax.swing.JLabel jpnl_img_etiqueta;
    private javax.swing.JPanel jpnl_sideMenu;
    private javax.swing.JTable jtbl_lista_produtos;
    // End of variables declaration//GEN-END:variables
}
